# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 262d338addf1af558ba2a3c8d4f4c574dae8b4d0ea1cdb7eb04958340a689eb8ca11c586994ac6f0c831536e24f58bef274643239b5dd741fa604b318929f1e9

test:
  secret_key_base: a32252501584686fb82678e3c97d230854512b82d608faccbfbd01d793e50c6fc39490d0f73d8763bb3777b54f1a61a5324f4d68c2df53c9f5ee97a26c8350bb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
